package com.studyassistant.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * StudyMaterial Entity — maps to the "study_materials" table in the database.
 *
 * Position in hierarchy:
 *   User → Topic → Note → StudyMaterial
 *
 * Each StudyMaterial represents a single uploaded file (PDF, image, doc, etc.)
 * attached to a specific Note.
 */
@Entity
// @Entity tells JPA: "This class is a database table."
// Hibernate will manage it — creating the table, inserting/updating/deleting rows.

@Table(name = "study_materials")
// @Table(name = ...) explicitly sets the table name.
// Without this, JPA would default to "StudyMaterial" (class name), which is inconsistent.
// Snake_case table names are the standard database convention.

@Data
// Lombok: auto-generates getters, setters, toString(), equals(), hashCode().
// You don't need to write any of those manually.

@Builder
// Lombok: lets you construct objects using the builder pattern:
//   StudyMaterial.builder().fileName("notes.pdf").fileSize(2048L).build();
// Much cleaner than calling a constructor with 7+ parameters.

@NoArgsConstructor
// Lombok: generates a no-argument constructor → required by JPA/Hibernate.
// JPA needs to instantiate the entity before populating its fields.

@AllArgsConstructor
// Lombok: generates a constructor with ALL fields as parameters.
// Needed because @Builder requires it when @NoArgsConstructor is present.

public class StudyMaterial {

    // ─────────────────────────────────────────
    // PRIMARY KEY
    // ─────────────────────────────────────────

    @Id
    // @Id marks this field as the PRIMARY KEY of the table.
    // Every JPA entity must have exactly one @Id field.

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // @GeneratedValue tells JPA: "Don't set this manually — the database generates it."
    // GenerationType.IDENTITY = auto-increment (1, 2, 3, ...) — works with MySQL/PostgreSQL.
    // This matches your User, Topic, and Note entities.

    private Long id;

    // ─────────────────────────────────────────
    // FILE METADATA FIELDS
    // ─────────────────────────────────────────

    @Column(name = "file_name", nullable = false)
    // @Column(name = ...) maps to a specific column name in the table.
    // nullable = false → adds a NOT NULL constraint at the database level.
    // "file_name" is the unique, sanitized name used for storage (e.g., UUID-based).

    private String fileName;
    // The stored filename on disk or cloud (e.g., "a3f2c1d4-notes.pdf").
    // Generated by the backend to avoid conflicts and special character issues.

    @Column(name = "original_file_name", nullable = false)
    // "original_file_name" stores what the user actually named their file.
    // This is shown to the user in the UI — not the sanitized storage name.

    private String originalFileName;
    // The filename the user uploaded (e.g., "Chapter 3 Notes.pdf").
    // Kept separately from fileName for display purposes.

    @Column(name = "file_type", nullable = false)
    // Stores the MIME type of the file.
    // Examples: "application/pdf", "image/jpeg", "application/msword"
    // Used when serving the file — tells the browser how to handle it.

    private String fileType;
    // The MIME type (content type) of the uploaded file.

    @Column(name = "file_size", nullable = false)
    // Stores file size in BYTES.
    // Long supports files up to ~9.2 exabytes — more than enough.
    // Using Long (not int) because int maxes out at ~2GB.

    private Long fileSize;
    // File size in bytes. Displayed as "2.4 MB" after conversion in the frontend.

    @Column(name = "file_path", nullable = false)
    // The absolute or relative path where the file is stored on the server.
    // Example: "/uploads/study-materials/a3f2c1d4-notes.pdf"
    // Or an S3 URL if you move to cloud storage later.

    private String filePath;
    // Location of the file on the server's filesystem or cloud storage.

    // ─────────────────────────────────────────
    // TIMESTAMP
    // ─────────────────────────────────────────

    @Column(name = "uploaded_at", nullable = false, updatable = false)
    // updatable = false → once set, this value NEVER changes via JPA updates.
    // This is intentional — an upload timestamp should be immutable.

    private LocalDateTime uploadedAt;
    // When this file was uploaded. Set automatically before saving (via @PrePersist below).

    @PrePersist
    // @PrePersist is a JPA lifecycle callback.
    // This method runs AUTOMATICALLY just before the entity is first saved to the database.
    // You don't need to set uploadedAt manually anywhere in your service code.

    protected void onCreate() {
        this.uploadedAt = LocalDateTime.now();
        // Sets the upload timestamp to the current server time at the moment of saving.
    }

    // ─────────────────────────────────────────
    // RELATIONSHIP — Many StudyMaterials → One Note
    // ─────────────────────────────────────────

    @ManyToOne(fetch = FetchType.LAZY)
    // @ManyToOne — "Many study materials belong to One note."
    //
    // fetch = FetchType.LAZY — IMPORTANT PERFORMANCE SETTING:
    //   LAZY  → Note is NOT loaded from DB until you explicitly call .getNote()
    //   EAGER → Note (and its Topic, and its User) would load immediately — wasteful.
    // Always use LAZY for @ManyToOne to avoid unintentional JOIN queries.

    @JoinColumn(name = "note_id", nullable = false)
    // @JoinColumn defines the FOREIGN KEY column in the study_materials table.
    // name = "note_id" → the column name in study_materials that holds the Note's ID.
    // nullable = false → every StudyMaterial MUST belong to a Note.

    private Note note;
    // The Note this file is attached to.
    // In the database, this becomes a "note_id" column (foreign key to notes.id).
}