package com.studyassistant.dto.request;

import jakarta.validation.constraints.NotBlank;

import jakarta.validation.constraints.Size;

/**
 * NoteRequest DTO — What the CLIENT sends TO the server.
 *
 * Used for:
 *   POST /api/topics/{topicId}/notes  → Create a new note
 *   PUT  /api/topics/{topicId}/notes/{id} → Update an existing note
 *
 * WHAT WE ACCEPT FROM THE USER:
 *   ✅ title    → The note heading
 *   ✅ content  → The note body
 *
 * WHAT WE DO NOT ACCEPT FROM THE USER (server controls these):
 *   ❌ id        → Auto-generated by the database
 *   ❌ createdAt → Set automatically on the server
 *   ❌ topic     → Taken from the URL path (e.g. /api/topics/3/notes),
 *                  NOT from the request body — this prevents users from
 *                  assigning notes to topics they don't own
 *
 * NOTE: No @Entity annotation here — this is NOT a database table.
 *       It is a plain Java object (POJO) just for carrying HTTP data.
 */
public class NoteRequest {

    /**
     * The title of the note.
     *
     * @NotBlank → Fails validation if title is:
     *             - null
     *             - empty string ""
     *             - only whitespace "   "
     *
     * @Size → Enforces length boundaries:
     *         min = 1    → At least 1 real character required
     *         max = 255  → Matches our DB column length limit
     *
     * If validation fails, Spring automatically returns HTTP 400 Bad Request
     * with an error message — before the request even reaches our Service.
     */
    @NotBlank(message = "Note title cannot be blank")
    @Size(min = 1, max = 255, message = "Note title must be between 1 and 255 characters")
    private String title;

    /**
     * The full study content of the note.
     *
     * @NotBlank → Content must not be empty.
     *             A note without content has no purpose.
     *
     * @Size → max = 10000 is a safety cap to prevent someone from
     *         sending a 50MB string and overloading the server.
     *         Adjust this limit based on your needs.
     *
     * No @Column here — this is not an entity, just a plain Java class.
     */
    @NotBlank(message = "Note content cannot be blank")
    @Size(min = 1, max = 10000, message = "Note content must be between 1 and 10000 characters")
    private String content;

    // ─────────────────────────────────────────────
    // DEFAULT CONSTRUCTOR
    // Required by Jackson (Spring's JSON library).
    // When Spring receives JSON from the HTTP request,
    // Jackson creates this object using the no-arg constructor
    // and then calls the setters to populate the fields.
    // ─────────────────────────────────────────────
    public NoteRequest() {
    }

    /**
     * Parameterized constructor — convenient for creating
     * NoteRequest objects in unit tests later.
     *
     * @param title   - Note heading
     * @param content - Note body text
     */
    public NoteRequest(String title, String content) {
        this.title = title;
        this.content = content;
    }

    // ─────────────────────────────────────────────
    // GETTERS AND SETTERS
    // Jackson needs getters to serialize (object → JSON)
    // and setters to deserialize (JSON → object).
    // ─────────────────────────────────────────────

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
}